### PR TITLE
718 simple milestones

### PR DESCRIPTION
**Pull request by campgurus**
Please take a look.  Depending on screen size, the icons in the timeline get covered by the text box.  actually, now that i think of it, we might be able to fix that using z-index attribute in css.

We have also talked about adding other categories of events. We could add an event_type attribute the article_milestone model and use that to automate changing the icon and the color of the circle, but I don't think we need that now.

### CODE REVIEW

**Comment by trystant** [comment]
We decided to take milestones out for now, so we can remove this PR, correct?

**Comment by rlgreen91** [comment]
Can you bring me up to speed on what milestones are and why we're (temporarily, I guess) removing them?

**Comment by trystant** [comment]
The milestones are part of a proposed timeline view of each case. As opposed to just posting links, we put the events of the case on a timeline and allow the user to journey through each one.  I think it is still a good goal, but we probably need to revamp how to make that happen.

**Comment by rlgreen91** [comment]
That is a good idea.  I will add that to the roadmap.

**Comment by rlgreen91** [comment]
Given that we are redoing our approach to milestones, I will be closing this PR.

**Pull request closed without merging**
