### PR TITLE
fix: adds some spacing to articles show page between nearby cases and map

### PR DESCRIPTION
**Pull request by silverli**
https://github.com/BOWiki/BOW/issues/959

### CODE REVIEW

**Comment by rlgreen91** [comment]
Hi @silverli, can you add a screenshot of the page with the change?  Typically you want to provide that when changing CSS or HTML.

**Comment by trystant** [comment]
Ready to merge as soon as I get the screenshot.

**Comment by silverli** [comment]
Hmmm, so I was one of the people working with Greg Greenlee on Saturday for the open source workshop.  I have the production database you sent him but am not sure how to import it. Can you provide some advice on this? Otherwise, my screenshot doesn't provide much information since there are no cases in my database.

**Comment by rlgreen91** [comment]
Hi @silverli, can you ping me in Slack?  Then I can walk you through recreating the database locally.

**Comment by rlgreen91** [comment]
Another PR has addressed the same issue.

**Pull request closed without merging**
