### PR TITLE
Address Geolocation issues

### PR DESCRIPTION
**Pull request by IsaacBell**
This was written to resolve issue #881  . Please check it out and let me know what you think.

All worked as intended from what I can tell  on my machines; let me know if that's not the case for others. I added a slight modification of the rake task from the geocoder docs for the back-generation of article coordinates. The command is to run that is:
`rake geocode_data:all CLASS=Article SLEEP=0.25 BATCH=100`

### CODE REVIEW

**Comment by trystant** [comment]
Hey @IsaacBell , it looks like the [Travis](https://travis-ci.org/BOWiki/BOW/builds/233431544) build failed for the PR. Considering that `master` is still green, would you mind looking into why the build is failing on your PR?  Thanks.

**Comment by IsaacBell** [comment]
Whoops, thought I'd commented already. Same issue with AWS environment
variables (aws_access_key_id, etc.) as pops up in the Issues for
development, because I don't have production key env variables set.

**Comment by trystant** [comment]
I think that you may need to be a member of the organization, @IsaacBell. I've just sent an invite. Once you accept, Travis should run the build *with* the environmental variables that you need.

**Comment by trystant** [comment]
@IsaacBell BTW, due to the way Github does permissions, you might need to reconnect your Github account to Travis in order for it to pick up the organization permissions.

**Comment by trystant** [comment]
So here's some additional information. Due to the way that [Travis](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions) handles pull requests from forks, the environmental variables will not get copied over to your fork, @IsaacBell. 

If I were you, I'd just work off of the BOWiki repository directly, and file your pull request from that repository. Does that make sense?

**Comment by IsaacBell** [comment]
Yes, makes sense, I'll do that.

**Pull request closed without merging**
